<?php

namespace App\Actions;

use App\DTOs\ActivityDetailData;
use App\DTOs\CreateListingData;
use App\DTOs\GuideDetailData;
use App\DTOs\HomeDetailData;
use App\DTOs\HotelDetailData;
use App\DTOs\RestaurantDetailData;
use App\DTOs\TourDetailData;
use App\Enums\ListingStatus;
use App\Enums\ListingType;
use App\Models\ActivityDetail;
use App\Models\GuideDetail;
use App\Models\HomeDetail;
use App\Models\HotelDetail;
use App\Models\Listing;
use App\Models\RestaurantDetail;
use App\Models\TourDetail;
use Illuminate\Support\Facades\DB;

class CreateListingAction
{
    /**
     * Create a new listing in draft status with all associated records.
     *
     * Creates the listing hub, translations, location, and the type-specific
     * detail record in a single transaction.
     */
    public function execute(CreateListingData $data): Listing
    {
        return DB::transaction(function () use ($data): Listing {
            // 1. Create the listing hub record
            $listing = Listing::create([
                'user_id'       => $data->userId,
                'type'          => $data->type->value,
                'status'        => ListingStatus::Draft->value,
                'price_from'    => $data->priceFrom,
                'contact_email' => $data->contactEmail,
                'contact_phone' => $data->contactPhone,
                'website_url'   => $data->websiteUrl,
                'social_links'  => $data->socialLinks,
            ]);

            // 2. Persist translations (slug will be generated by HasSlug after az translation exists)
            foreach ($data->translations as $translation) {
                $listing->translations()->create($translation->toArray());
            }

            // Regenerate slug now that the az translation exists
            $listing->generateSlug();
            $listing->save();

            // 3. Persist location
            $listing->location()->create($data->location->toArray());

            // 4. Persist the type-specific detail
            $this->createDetail($listing, $data->detail);

            // 5. Sync categories and amenities
            if (! empty($data->categoryIds)) {
                $listing->categories()->sync($data->categoryIds);
            }

            if (! empty($data->amenityIds)) {
                $listing->amenities()->sync($data->amenityIds);
            }

            return $listing->fresh(['translations', 'location', 'detail']);
        });
    }

    private function createDetail(
        Listing $listing,
        HotelDetailData|HomeDetailData|TourDetailData|ActivityDetailData|GuideDetailData|RestaurantDetailData $detailData,
    ): void {
        $payload = array_merge(['listing_id' => $listing->id], $detailData->toArray());

        match ($listing->type) {
            ListingType::Hotel      => HotelDetail::create($payload),
            ListingType::Home       => HomeDetail::create($payload),
            ListingType::Tour       => TourDetail::create($payload),
            ListingType::Activity   => ActivityDetail::create($payload),
            ListingType::Guide      => GuideDetail::create($payload),
            ListingType::Restaurant => RestaurantDetail::create($payload),
        };
    }
}
